var table = [
    { 'value': 0x1ff8     , 'len': 13 },
    { 'value': 0x7fffd8   , 'len': 23 },
    { 'value': 0xfffffe2  , 'len': 28 },
    { 'value': 0xfffffe3  , 'len': 28 },
    { 'value': 0xfffffe4  , 'len': 28 },
    { 'value': 0xfffffe5  , 'len': 28 },
    { 'value': 0xfffffe6  , 'len': 28 },
    { 'value': 0xfffffe7  , 'len': 28 },
    { 'value': 0xfffffe8  , 'len': 28 },
    { 'value': 0xffffea   , 'len': 24 },
    { 'value': 0x3ffffffc , 'len': 30 },
    { 'value': 0xfffffe9  , 'len': 28 },
    { 'value': 0xfffffea  , 'len': 28 },
    { 'value': 0x3ffffffd , 'len': 30 },
    { 'value': 0xfffffeb  , 'len': 28 },
    { 'value': 0xfffffec  , 'len': 28 },
    { 'value': 0xfffffed  , 'len': 28 },
    { 'value': 0xfffffee  , 'len': 28 },
    { 'value': 0xfffffef  , 'len': 28 },
    { 'value': 0xffffff0  , 'len': 28 },
    { 'value': 0xffffff1  , 'len': 28 },
    { 'value': 0xffffff2  , 'len': 28 },
    { 'value': 0x3ffffffe , 'len': 30 },
    { 'value': 0xffffff3  , 'len': 28 },
    { 'value': 0xffffff4  , 'len': 28 },
    { 'value': 0xffffff5  , 'len': 28 },
    { 'value': 0xffffff6  , 'len': 28 },
    { 'value': 0xffffff7  , 'len': 28 },
    { 'value': 0xffffff8  , 'len': 28 },
    { 'value': 0xffffff9  , 'len': 28 },
    { 'value': 0xffffffa  , 'len': 28 },
    { 'value': 0xffffffb  , 'len': 28 },
    { 'value': 0x14       , 'len':  6 },
    { 'value': 0x3f8      , 'len': 10 },
    { 'value': 0x3f9      , 'len': 10 },
    { 'value': 0xffa      , 'len': 12 },
    { 'value': 0x1ff9     , 'len': 13 },
    { 'value': 0x15       , 'len':  6 },
    { 'value': 0xf8       , 'len':  8 },
    { 'value': 0x7fa      , 'len': 11 },
    { 'value': 0x3fa      , 'len': 10 },
    { 'value': 0x3fb      , 'len': 10 },
    { 'value': 0xf9       , 'len':  8 },
    { 'value': 0x7fb      , 'len': 11 },
    { 'value': 0xfa       , 'len':  8 },
    { 'value': 0x16       , 'len':  6 },
    { 'value': 0x17       , 'len':  6 },
    { 'value': 0x18       , 'len':  6 },
    { 'value': 0x0        , 'len':  5 },
    { 'value': 0x1        , 'len':  5 },
    { 'value': 0x2        , 'len':  5 },
    { 'value': 0x19       , 'len':  6 },
    { 'value': 0x1a       , 'len':  6 },
    { 'value': 0x1b       , 'len':  6 },
    { 'value': 0x1c       , 'len':  6 },
    { 'value': 0x1d       , 'len':  6 },
    { 'value': 0x1e       , 'len':  6 },
    { 'value': 0x1f       , 'len':  6 },
    { 'value': 0x5c       , 'len':  7 },
    { 'value': 0xfb       , 'len':  8 },
    { 'value': 0x7ffc     , 'len': 15 },
    { 'value': 0x20       , 'len':  6 },
    { 'value': 0xffb      , 'len': 12 },
    { 'value': 0x3fc      , 'len': 10 },
    { 'value': 0x1ffa     , 'len': 13 },
    { 'value': 0x21       , 'len':  6 },
    { 'value': 0x5d       , 'len':  7 },
    { 'value': 0x5e       , 'len':  7 },
    { 'value': 0x5f       , 'len':  7 },
    { 'value': 0x60       , 'len':  7 },
    { 'value': 0x61       , 'len':  7 },
    { 'value': 0x62       , 'len':  7 },
    { 'value': 0x63       , 'len':  7 },
    { 'value': 0x64       , 'len':  7 },
    { 'value': 0x65       , 'len':  7 },
    { 'value': 0x66       , 'len':  7 },
    { 'value': 0x67       , 'len':  7 },
    { 'value': 0x68       , 'len':  7 },
    { 'value': 0x69       , 'len':  7 },
    { 'value': 0x6a       , 'len':  7 },
    { 'value': 0x6b       , 'len':  7 },
    { 'value': 0x6c       , 'len':  7 },
    { 'value': 0x6d       , 'len':  7 },
    { 'value': 0x6e       , 'len':  7 },
    { 'value': 0x6f       , 'len':  7 },
    { 'value': 0x70       , 'len':  7 },
    { 'value': 0x71       , 'len':  7 },
    { 'value': 0x72       , 'len':  7 },
    { 'value': 0xfc       , 'len':  8 },
    { 'value': 0x73       , 'len':  7 },
    { 'value': 0xfd       , 'len':  8 },
    { 'value': 0x1ffb     , 'len': 13 },
    { 'value': 0x7fff0    , 'len': 19 },
    { 'value': 0x1ffc     , 'len': 13 },
    { 'value': 0x3ffc     , 'len': 14 },
    { 'value': 0x22       , 'len':  6 },
    { 'value': 0x7ffd     , 'len': 15 },
    { 'value': 0x3        , 'len':  5 },
    { 'value': 0x23       , 'len':  6 },
    { 'value': 0x4        , 'len':  5 },
    { 'value': 0x24       , 'len':  6 },
    { 'value': 0x5        , 'len':  5 },
    { 'value': 0x25       , 'len':  6 },
    { 'value': 0x26       , 'len':  6 },
    { 'value': 0x27       , 'len':  6 },
    { 'value': 0x6        , 'len':  5 },
    { 'value': 0x74       , 'len':  7 },
    { 'value': 0x75       , 'len':  7 },
    { 'value': 0x28       , 'len':  6 },
    { 'value': 0x29       , 'len':  6 },
    { 'value': 0x2a       , 'len':  6 },
    { 'value': 0x7        , 'len':  5 },
    { 'value': 0x2b       , 'len':  6 },
    { 'value': 0x76       , 'len':  7 },
    { 'value': 0x2c       , 'len':  6 },
    { 'value': 0x8        , 'len':  5 },
    { 'value': 0x9        , 'len':  5 },
    { 'value': 0x2d       , 'len':  6 },
    { 'value': 0x77       , 'len':  7 },
    { 'value': 0x78       , 'len':  7 },
    { 'value': 0x79       , 'len':  7 },
    { 'value': 0x7a       , 'len':  7 },
    { 'value': 0x7b       , 'len':  7 },
    { 'value': 0x7ffe     , 'len': 15 },
    { 'value': 0x7fc      , 'len': 11 },
    { 'value': 0x3ffd     , 'len': 14 },
    { 'value': 0x1ffd     , 'len': 13 },
    { 'value': 0xffffffc  , 'len': 28 },
    { 'value': 0xfffe6    , 'len': 20 },
    { 'value': 0x3fffd2   , 'len': 22 },
    { 'value': 0xfffe7    , 'len': 20 },
    { 'value': 0xfffe8    , 'len': 20 },
    { 'value': 0x3fffd3   , 'len': 22 },
    { 'value': 0x3fffd4   , 'len': 22 },
    { 'value': 0x3fffd5   , 'len': 22 },
    { 'value': 0x7fffd9   , 'len': 23 },
    { 'value': 0x3fffd6   , 'len': 22 },
    { 'value': 0x7fffda   , 'len': 23 },
    { 'value': 0x7fffdb   , 'len': 23 },
    { 'value': 0x7fffdc   , 'len': 23 },
    { 'value': 0x7fffdd   , 'len': 23 },
    { 'value': 0x7fffde   , 'len': 23 },
    { 'value': 0xffffeb   , 'len': 24 },
    { 'value': 0x7fffdf   , 'len': 23 },
    { 'value': 0xffffec   , 'len': 24 },
    { 'value': 0xffffed   , 'len': 24 },
    { 'value': 0x3fffd7   , 'len': 22 },
    { 'value': 0x7fffe0   , 'len': 23 },
    { 'value': 0xffffee   , 'len': 24 },
    { 'value': 0x7fffe1   , 'len': 23 },
    { 'value': 0x7fffe2   , 'len': 23 },
    { 'value': 0x7fffe3   , 'len': 23 },
    { 'value': 0x7fffe4   , 'len': 23 },
    { 'value': 0x1fffdc   , 'len': 21 },
    { 'value': 0x3fffd8   , 'len': 22 },
    { 'value': 0x7fffe5   , 'len': 23 },
    { 'value': 0x3fffd9   , 'len': 22 },
    { 'value': 0x7fffe6   , 'len': 23 },
    { 'value': 0x7fffe7   , 'len': 23 },
    { 'value': 0xffffef   , 'len': 24 },
    { 'value': 0x3fffda   , 'len': 22 },
    { 'value': 0x1fffdd   , 'len': 21 },
    { 'value': 0xfffe9    , 'len': 20 },
    { 'value': 0x3fffdb   , 'len': 22 },
    { 'value': 0x3fffdc   , 'len': 22 },
    { 'value': 0x7fffe8   , 'len': 23 },
    { 'value': 0x7fffe9   , 'len': 23 },
    { 'value': 0x1fffde   , 'len': 21 },
    { 'value': 0x7fffea   , 'len': 23 },
    { 'value': 0x3fffdd   , 'len': 22 },
    { 'value': 0x3fffde   , 'len': 22 },
    { 'value': 0xfffff0   , 'len': 24 },
    { 'value': 0x1fffdf   , 'len': 21 },
    { 'value': 0x3fffdf   , 'len': 22 },
    { 'value': 0x7fffeb   , 'len': 23 },
    { 'value': 0x7fffec   , 'len': 23 },
    { 'value': 0x1fffe0   , 'len': 21 },
    { 'value': 0x1fffe1   , 'len': 21 },
    { 'value': 0x3fffe0   , 'len': 22 },
    { 'value': 0x1fffe2   , 'len': 21 },
    { 'value': 0x7fffed   , 'len': 23 },
    { 'value': 0x3fffe1   , 'len': 22 },
    { 'value': 0x7fffee   , 'len': 23 },
    { 'value': 0x7fffef   , 'len': 23 },
    { 'value': 0xfffea    , 'len': 20 },
    { 'value': 0x3fffe2   , 'len': 22 },
    { 'value': 0x3fffe3   , 'len': 22 },
    { 'value': 0x3fffe4   , 'len': 22 },
    { 'value': 0x7ffff0   , 'len': 23 },
    { 'value': 0x3fffe5   , 'len': 22 },
    { 'value': 0x3fffe6   , 'len': 22 },
    { 'value': 0x7ffff1   , 'len': 23 },
    { 'value': 0x3ffffe0  , 'len': 26 },
    { 'value': 0x3ffffe1  , 'len': 26 },
    { 'value': 0xfffeb    , 'len': 20 },
    { 'value': 0x7fff1    , 'len': 19 },
    { 'value': 0x3fffe7   , 'len': 22 },
    { 'value': 0x7ffff2   , 'len': 23 },
    { 'value': 0x3fffe8   , 'len': 22 },
    { 'value': 0x1ffffec  , 'len': 25 },
    { 'value': 0x3ffffe2  , 'len': 26 },
    { 'value': 0x3ffffe3  , 'len': 26 },
    { 'value': 0x3ffffe4  , 'len': 26 },
    { 'value': 0x7ffffde  , 'len': 27 },
    { 'value': 0x7ffffdf  , 'len': 27 },
    { 'value': 0x3ffffe5  , 'len': 26 },
    { 'value': 0xfffff1   , 'len': 24 },
    { 'value': 0x1ffffed  , 'len': 25 },
    { 'value': 0x7fff2    , 'len': 19 },
    { 'value': 0x1fffe3   , 'len': 21 },
    { 'value': 0x3ffffe6  , 'len': 26 },
    { 'value': 0x7ffffe0  , 'len': 27 },
    { 'value': 0x7ffffe1  , 'len': 27 },
    { 'value': 0x3ffffe7  , 'len': 26 },
    { 'value': 0x7ffffe2  , 'len': 27 },
    { 'value': 0xfffff2   , 'len': 24 },
    { 'value': 0x1fffe4   , 'len': 21 },
    { 'value': 0x1fffe5   , 'len': 21 },
    { 'value': 0x3ffffe8  , 'len': 26 },
    { 'value': 0x3ffffe9  , 'len': 26 },
    { 'value': 0xffffffd  , 'len': 28 },
    { 'value': 0x7ffffe3  , 'len': 27 },
    { 'value': 0x7ffffe4  , 'len': 27 },
    { 'value': 0x7ffffe5  , 'len': 27 },
    { 'value': 0xfffec    , 'len': 20 },
    { 'value': 0xfffff3   , 'len': 24 },
    { 'value': 0xfffed    , 'len': 20 },
    { 'value': 0x1fffe6   , 'len': 21 },
    { 'value': 0x3fffe9   , 'len': 22 },
    { 'value': 0x1fffe7   , 'len': 21 },
    { 'value': 0x1fffe8   , 'len': 21 },
    { 'value': 0x7ffff3   , 'len': 23 },
    { 'value': 0x3fffea   , 'len': 22 },
    { 'value': 0x3fffeb   , 'len': 22 },
    { 'value': 0x1ffffee  , 'len': 25 },
    { 'value': 0x1ffffef  , 'len': 25 },
    { 'value': 0xfffff4   , 'len': 24 },
    { 'value': 0xfffff5   , 'len': 24 },
    { 'value': 0x3ffffea  , 'len': 26 },
    { 'value': 0x7ffff4   , 'len': 23 },
    { 'value': 0x3ffffeb  , 'len': 26 },
    { 'value': 0x7ffffe6  , 'len': 27 },
    { 'value': 0x3ffffec  , 'len': 26 },
    { 'value': 0x3ffffed  , 'len': 26 },
    { 'value': 0x7ffffe7  , 'len': 27 },
    { 'value': 0x7ffffe8  , 'len': 27 },
    { 'value': 0x7ffffe9  , 'len': 27 },
    { 'value': 0x7ffffea  , 'len': 27 },
    { 'value': 0x7ffffeb  , 'len': 27 },
    { 'value': 0xffffffe  , 'len': 28 },
    { 'value': 0x7ffffec  , 'len': 27 },
    { 'value': 0x7ffffed  , 'len': 27 },
    { 'value': 0x7ffffee  , 'len': 27 },
    { 'value': 0x7ffffef  , 'len': 27 },
    { 'value': 0x7fffff0  , 'len': 27 },
    { 'value': 0x3ffffee  , 'len': 26 },
    { 'value': 0x3fffffff , 'len': 30 },
];

var dTable = [];
dTable[5] = [
    { 'value': 0x0        , 'output':  48 },
    { 'value': 0x1        , 'output':  49 },
    { 'value': 0x2        , 'output':  50 },
    { 'value': 0x3        , 'output':  97 },
    { 'value': 0x4        , 'output':  99 },
    { 'value': 0x5        , 'output':  101 },
    { 'value': 0x6        , 'output':  105 },
    { 'value': 0x7        , 'output':  111 },
    { 'value': 0x8        , 'output':  115 },
    { 'value': 0x9        , 'output':  116 },
];
dTable[6] = [
    { 'value': 0x14       , 'output':  32 },
    { 'value': 0x15       , 'output':  37 },
    { 'value': 0x16       , 'output':  45 },
    { 'value': 0x17       , 'output':  46 },
    { 'value': 0x18       , 'output':  47 },
    { 'value': 0x19       , 'output':  51 },
    { 'value': 0x1a       , 'output':  52 },
    { 'value': 0x1b       , 'output':  53 },
    { 'value': 0x1c       , 'output':  54 },
    { 'value': 0x1d       , 'output':  55 },
    { 'value': 0x1e       , 'output':  56 },
    { 'value': 0x1f       , 'output':  57 },
    { 'value': 0x20       , 'output':  61 },
    { 'value': 0x21       , 'output':  65 },
    { 'value': 0x22       , 'output':  95 },
    { 'value': 0x23       , 'output':  98 },
    { 'value': 0x24       , 'output': 100 },
    { 'value': 0x25       , 'output': 102 },
    { 'value': 0x26       , 'output': 103 },
    { 'value': 0x27       , 'output': 104 },
    { 'value': 0x28       , 'output': 108 },
    { 'value': 0x29       , 'output': 109 },
    { 'value': 0x2a       , 'output': 110 },
    { 'value': 0x2b       , 'output': 112 },
    { 'value': 0x2c       , 'output': 114 },
    { 'value': 0x2d       , 'output': 117 },
];
dTable[7] = [
    { 'value': 0x5c       , 'output':  58 },
    { 'value': 0x5d       , 'output':  66 },
    { 'value': 0x5e       , 'output':  67 },
    { 'value': 0x5f       , 'output':  68 },
    { 'value': 0x60       , 'output':  69 },
    { 'value': 0x61       , 'output':  70 },
    { 'value': 0x62       , 'output':  71 },
    { 'value': 0x63       , 'output':  72 },
    { 'value': 0x64       , 'output':  73 },
    { 'value': 0x65       , 'output':  74 },
    { 'value': 0x66       , 'output':  75 },
    { 'value': 0x67       , 'output':  76 },
    { 'value': 0x68       , 'output':  77 },
    { 'value': 0x69       , 'output':  78 },
    { 'value': 0x6a       , 'output':  79 },
    { 'value': 0x6b       , 'output':  80 },
    { 'value': 0x6c       , 'output':  81 },
    { 'value': 0x6d       , 'output':  82 },
    { 'value': 0x6e       , 'output':  83 },
    { 'value': 0x6f       , 'output':  84 },
    { 'value': 0x70       , 'output':  85 },
    { 'value': 0x71       , 'output':  86 },
    { 'value': 0x72       , 'output':  87 },
    { 'value': 0x73       , 'output':  89 },
    { 'value': 0x74       , 'output': 106 },
    { 'value': 0x75       , 'output': 107 },
    { 'value': 0x76       , 'output': 113 },
    { 'value': 0x77       , 'output': 118 },
    { 'value': 0x78       , 'output': 119 },
    { 'value': 0x79       , 'output': 120 },
    { 'value': 0x7a       , 'output': 121 },
    { 'value': 0x7b       , 'output': 122 },
];
dTable[9] = [
];
dTable[8] = [
    { 'value': 0xf8       , 'output':  38 },
    { 'value': 0xf9       , 'output':  42 },
    { 'value': 0xfa       , 'output':  44 },
    { 'value': 0xfb       , 'output':  59 },
    { 'value': 0xfc       , 'output':  88 },
    { 'value': 0xfd       , 'output':  90 },
];
dTable[10] = [
    { 'value': 0x3f8      , 'output':  33 },
    { 'value': 0x3f9      , 'output':  34 },
    { 'value': 0x3fa      , 'output':  40 },
    { 'value': 0x3fb      , 'output':  41 },
    { 'value': 0x3fc      , 'output':  63 },
];
dTable[11] = [
    { 'value': 0x7fa      , 'output':  39 },
    { 'value': 0x7fb      , 'output':  43 },
    { 'value': 0x7fc      , 'output': 124 },
];
dTable[12] = [
    { 'value': 0xffa      , 'output':  35 },
    { 'value': 0xffb      , 'output':  62 },
];
dTable[13] = [
    { 'value': 0x1ff8     , 'output':   0 },
    { 'value': 0x1ff9     , 'output':  36 },
    { 'value': 0x1ffa     , 'output':  64 },
    { 'value': 0x1ffb     , 'output':  91 },
    { 'value': 0x1ffc     , 'output':  93 },
    { 'value': 0x1ffd     , 'output': 126 },
];
dTable[14] = [
    { 'value': 0x3ffc     , 'output':  94 },
    { 'value': 0x3ffd     , 'output': 125 },
];
dTable[15] = [
    { 'value': 0x7ffc     , 'output':  60 },
    { 'value': 0x7ffd     , 'output':  96 },
    { 'value': 0x7ffe     , 'output': 123 },
];
dTable[16] = [
];
dTable[17] = [
];
dTable[18] = [
];
dTable[19] = [
    { 'value': 0x7fff0    , 'output':  92 },
    { 'value': 0x7fff1    , 'output': 195 },
    { 'value': 0x7fff2    , 'output': 208 },
];

module.exports.encode = function (data) {
};
module.exports.decode = function (data) {
    var i, j, k, code = 0, n = 0;
    var output = '';
    for (i = 0; i < data.length; i++) {
        for (j = 0x80; j > 0; j = j >>> 1) {
            code = code << 1;
            n++;
            code += (data[i] & j) ? 1 : 0;
            if (n < 5) {
                continue;
            }
            if (dTable[n]) {
                for (k = 0; k < dTable[n].length; k++) {
                    if (dTable[n][k].value === code) {
                        output += String.fromCharCode(dTable[n][k].output);
                        code = 0;
                        n = 0;
                        break;
                    }
                }
            } else {
                for (k = 0; k <= 256; k++) {
                    if (table[k].len === n && table[k].value === code) {
                        output += String.fromCharCode(k);
                        code = 0;
                        n = 0;
                        break;
                    }
                }
            }
        }
    }
    return output;
};
